apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: ldonleycb/hackers-web
      version:
        type: string
        default: 3.0-0.0.50
      digest:
        type: string
        default: sha256:798076c4c37f66435086bafc310ba324a8908e6c2ab76922ff6fea59dd113c33
      url:
        type: string
        default: ldonleycb/hackers-web:3.0-0.0.50  

jobs:
  republish:
    steps:
      - name: republish to delete
        with:
          version: ${{ inputs.version }}
          url: ${{ inputs.url }}
          digest: ${{ inputs.digest }}
          name: ${{ inputs.name }}
        uses: cloudbees-io/register-build-artifact@v1
